In [ ]:
from google.colab import files
uploaded = files.upload()

Saving ICE_Detention_Trends new.csv to ICE_Detention_Trends new.csv

In [ ]:
#
import pandas as pd
import numpy as np
df = pd.read_csv("ICE_Detention_Trends new.csv")
# f = pd.read_csv("house_data.csv") # This line caused the FileNotFoundError
df

            date  daily_pop  midnight_pop  book_in  book_out
0     2008-10-01    33876.0       32589.0   1306.0    1287.0
1     2008-10-02    33961.0       32475.0   1372.0    1486.0
2     2008-10-03    33762.0       32036.0   1287.0    1726.0
3     2008-10-04    32440.0       32024.0    404.0     416.0
4     2008-10-05    32299.0       32241.0    275.0      58.0
...          ...        ...           ...      ...       ...
6219  2025-10-11    62178.0       61501.0    796.0     677.0
6220  2025-10-12    62102.0       61432.0    601.0     670.0
6221  2025-10-13    62180.0       61365.0    748.0     815.0
6222  2025-10-14    62816.0       61820.0   1451.0     996.0
6223  2025-10-15    63240.0       61672.0   1420.0    1568.0

[6224 rows x 5 columns]

In [ ]:
df.shape

(6224, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6224 entries, 0 to 6223
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          6224 non-null   object
 1   daily_pop     6224 non-null   float64
 2   midnight_pop  6224 non-null   float64
 3   book_in       6224 non-null   float64
 4   book_out      6224 non-null   float64
dtypes: float64(4), object(1)
memory usage: 243.3+ KB

In [ ]:
df.head(10)

         date  daily_pop  midnight_pop  book_in  book_out
0  2008-10-01    33876.0       32589.0   1306.0    1287.0
1  2008-10-02    33961.0       32475.0   1372.0    1486.0
2  2008-10-03    33762.0       32036.0   1287.0    1726.0
3  2008-10-04    32440.0       32024.0    404.0     416.0
4  2008-10-05    32299.0       32241.0    275.0      58.0
5  2008-10-06    33683.0       32546.0   1442.0    1137.0
6  2008-10-07    33927.0       32519.0   1381.0    1408.0
7  2008-10-08    34193.0       32656.0   1674.0    1537.0
8  2008-10-09    33913.0       32189.0   1257.0    1724.0
9  2008-10-10    33731.0       32072.0   1542.0    1659.0

In [ ]:
df.tail()

            date  daily_pop  midnight_pop  book_in  book_out
6219  2025-10-11    62178.0       61501.0    796.0     677.0
6220  2025-10-12    62102.0       61432.0    601.0     670.0
6221  2025-10-13    62180.0       61365.0    748.0     815.0
6222  2025-10-14    62816.0       61820.0   1451.0     996.0
6223  2025-10-15    63240.0       61672.0   1420.0    1568.0

In [ ]:
df.describe()

          daily_pop  midnight_pop      book_in     book_out
count   6224.000000   6224.000000  6224.000000  6224.000000
mean   34764.509479  33830.122269   939.372751   934.387211
std     8696.240472   8580.340402   464.273624   567.266902
min    13628.000000  13282.000000    52.000000     8.000000
25%    30481.000000  29648.750000   526.000000   381.000000
50%    34269.500000  33206.000000   941.000000   995.000000
75%    38912.250000  37871.750000  1313.000000  1384.250000
max    63240.000000  61923.000000  2480.000000  2565.000000

In [ ]:
df.tail(10)

            date  daily_pop  midnight_pop  book_in  book_out
6214  2025-10-06    62275.0       61193.0   1178.0    1082.0
6215  2025-10-07    62654.0       61131.0   1461.0    1523.0
6216  2025-10-08    62641.0       60998.0   1510.0    1643.0
6217  2025-10-09    62504.0       61168.0   1506.0    1336.0
6218  2025-10-10    62706.0       61382.0   1538.0    1324.0
6219  2025-10-11    62178.0       61501.0    796.0     677.0
6220  2025-10-12    62102.0       61432.0    601.0     670.0
6221  2025-10-13    62180.0       61365.0    748.0     815.0
6222  2025-10-14    62816.0       61820.0   1451.0     996.0
6223  2025-10-15    63240.0       61672.0   1420.0    1568.0

Step 2 Identify missing values

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6224 entries, 0 to 6223
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          6224 non-null   object
 1   daily_pop     6224 non-null   float64
 2   midnight_pop  6224 non-null   float64
 3   book_in       6224 non-null   float64
 4   book_out      6224 non-null   float64
dtypes: float64(4), object(1)
memory usage: 243.3+ KB

In [ ]:
df.isnull()

       date  daily_pop  midnight_pop  book_in  book_out
0     False      False         False    False     False
1     False      False         False    False     False
2     False      False         False    False     False
3     False      False         False    False     False
4     False      False         False    False     False
...     ...        ...           ...      ...       ...
6219  False      False         False    False     False
6220  False      False         False    False     False
6221  False      False         False    False     False
6222  False      False         False    False     False
6223  False      False         False    False     False

[6224 rows x 5 columns]

In [ ]:
df.isnull().sum()

date            0
daily_pop       0
midnight_pop    0
book_in         0
book_out        0
dtype: int64

In [ ]:
df.isnull().sum().sum()
df['date'].isna().sum()

for i in df.columns:
 print(i)

date
daily_pop
midnight_pop
book_in
book_out

In [ ]:
for i in df.columns:
 print(i , df[i].dtypes )

date object
daily_pop float64
midnight_pop float64
book_in float64
book_out float64

In [ ]:
for i in df.columns:
 print(i , df[i].dtypes, df[i].isna().sum() )

date object 0
daily_pop float64 0
midnight_pop float64 0
book_in float64 0
book_out float64 0

In [ ]:
for i in df.columns:
 if(df[i].isna().sum() != 0):
  print(i , df[i].dtypes, df[i].isna().sum())

In [ ]:
for i in df.columns:
 if(df[i].isna().sum() != 0 and df[i].dtypes=='object'):
  print(i , df[i].dtypes, df[i].isna().sum())